#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan  9 14:44:30 2020

@author: weizhong
"""

from Bio import SeqIO
import os
from subprocess import run
import numpy as np

def getHHSuiteFiles(fastafile, outdir="."):
    inputfile = 'input.fasta'
    for seq_record in SeqIO.parse(fastafile, 'fasta'):
        print("\r{}".format(seq_record.id), end="")
        if os.path.exists(inputfile):
            os.remove(inputfile)
        SeqIO.write(seq_record, inputfile, 'fasta')
        
        hitresult = os.path.join(outdir, seq_record.id)
        if os.path.exists(hitresult):
            os.remove(hitresult)
            
        #cmd = ["hhblits", "-i", inputfile, "-o", hitresult, "-n", "1", "-d", "/home/weizhong/software/hh-suite/uniclust30_2018_08/uniclust30_2018_08"]
        cmd = ['hhblits -d /home/weizhong/software/hh-suite/uniclust30_2018_08/uniclust30_2018_08 -ohhm', hitresult, '-i', inputfile, '-v 0 -maxres 40000 -cpu 4 -Z 0'] 
        cmd = " ".join(cmd)
        
        run(cmd, shell=True)
        
        if not os.path.exists(hitresult):
            print("\r{} does not have hh-suite profile".format(seq_record.id))

"""
read the profile generated by hh-suite
"""
def read_hhm(hhm_file):
    f = open(hhm_file)
    line = f.readline()
    while line[0] != '#':
        line = f.readline()
    f.readline()
    f.readline()
    f.readline()
    f.readline()
    seq = []
    extras = np.zeros([0, 10])
    prob = np.zeros([0, 20])
    line = f.readline()
    while line[0:2] != '//':
        lineinfo = line.split()
        seq.append(lineinfo[0])
        probs_ = [2 ** (-float(lineinfo[i]) / 1000) if lineinfo[i] != '*' else 0. for i in range(2, 22)]
        prob = np.concatenate((prob, np.matrix(probs_)), axis=0)
        line = f.readline()
        lineinfo = line.split()
        extras_ = [2 ** (-float(lineinfo[i]) / 1000) if lineinfo[i] != '*' else 0. for i in range(0, 10)]
        extras = np.concatenate((extras, np.matrix(extras_)), axis=0)
        line = f.readline()
        assert len(line.strip()) == 0
        line = f.readline()
    # return (''.join(seq),prob,extras)
    return (seq, np.concatenate((prob, extras), axis=1))
if __name__ == "__main__":
    fastafile = '/home/weizhong/Repoes/PDNA_CNN/PDNA_Data/TargetDNA/PDNA-TEST_sequence.fasta'
    outdir = '/home/weizhong/Repoes/PDNA_CNN/PDNA_Data/PDNA543_hhm'
    #getHHSuiteFiles(fastafile,outdir)
    #a = readHhsuiteProfile(os.path.join(outdir,'1A0A_A'))
    files = os.listdir(outdir)
    lshhm = []
    for f in files:
        hhm_file = os.path.join(outdir, f)
        lshhm.append(read_hhm(hhm_file))
    np.save('/home/weizhong/Repoes/PDNA_CNN/PDNA_Data/PDNA543_hhm.npy', lshhm)
        